
--GRANT CONNECT TO AUTEST;
--
--GRANT CREATE TABLE, CREATE PROCEDURE TO AUTEST;
--
GRANT UNLIMITED TABLESPACE TO AUTEST;
AUDIT ALL BY AUTEST BY ACCESS;

AUDIT EXECUTE PROCEDURE BY AUTEST BY ACCESS;
AUDIT SESSION WHENEVER NOT SUCCESSFUL;



SELECT *
FROM DBA_AUDIT_TRAIL
WHERE USERNAME = 'TRGDV0001'
ORDER BY TIMESTAMP;

SELECT * FROM AUDITABLE_SYSTEM_ACTIONS;

select * from OLS_ADMIN.UV_TRUONGDONVI_PHANCONG_2;



